### ISSUE TITLE
Error thrown on tags without attributes

### ISSUE THREAD

**Issue by debben** [jamesjieye/html-webpack-exclude-assets-plugin#4]
Hi,

I'm using the [style-ext-html-webpack-plugin](https://www.npmjs.com/package/style-ext-html-webpack-plugin) in addition to the html-webpack-exclude-plugin. The style-ext-html-webpack-plugin is executed before the exclude plugin and generates a <script> tag without any attributes. This breaks the exclude plugin when used together. 

```
Html Webpack Plugin:
<pre>
  TypeError: Cannot read property 'src' of undefined
  
  - index.js:47 
    [src]/[html-webpack-exclude-assets-plugin]/index.js:47:57
  
  - Array.forEach
  
  - index.js:46 HtmlWebpackExcludeAssetsPlugin.processAssets
    [src]/[html-webpack-exclude-assets-plugin]/index.js:46:19
  
  - index.js:29 Compilation.<anonymous>
    [src]/[html-webpack-exclude-assets-plugin]/index.js:29:25
  
```

The forEach in question should probably short-circuit on the tag having any attributes at all:
```
  pluginData.head.forEach(function (tag) {
    if (!tag.attributes || !self.isExcluded(excludePatterns, tag.attributes.src || tag.attributes.href)) {
      head.push(tag);
    }
  });
```

**Comment by jamesjieye** [comment]
@debben Thank you for the fix!
